# Generated by Django 3.0.7 on 2020-07-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200730_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
