# Generated by Django 3.0.7 on 2020-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
