# Generated by Django 3.0.7 on 2020-07-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200726_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.Size'),
        ),
    ]
