# Generated by Django 3.0.7 on 2020-07-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primaryImage',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
